### PR TITLE
fix: Fix jobs dict not existing

### PR DESCRIPTION
**Pull request by NeoLegends**
```
}, feature_extraction=None, stm_args=None, stm_paths={'dev-other': <Path /u/mgunz/setups/2023-04--thesis-baselines/...rt/CorpusToStmJob.cWMBwQxemXAT/output/corpus.stm>})
    184
    185             for job_type in ["search", "lat2ctm", "score", "optlm"]:
--> 186                 self.jobs[corpus_key][job_type] = {}
        self.jobs = {}
        corpus_key = 'dev-other'
        job_type = 'search'
    187
    188     @staticmethod

KeyError: 'dev-other'
```

### CODE REVIEW

**Review by christophmluscher — CHANGES_REQUESTED** [review]
I don't like the place of that code that much...

**Comment by christophmluscher** [comment]
I ll take a look at home

**Review by JackTemaki — CHANGES_REQUESTED** [review]
I agree with @christophmluscher that the position it is now is clearly wrong. `_get_scales_string` should not initialize things. @NeoLegends can determine why this is not intialized? is `init_eval_datasets` never called in your case? I would assume the actual error here is somewhere else.

**Comment by NeoLegends** [comment]
The issue is that the `corpus_key` there isn't actually the corpus key, but the "derived" corpus key (as the code calls it) which additionally includes various scales, like the prior scales and so on. But I agree this is a bandaid fix, not a proper solution. Let's do this differently.

**Pull request closed without merging**
