### PR TITLE
fix: no automatic upper casing

### PR DESCRIPTION
**Pull request by christophmluscher**
fixes automatic upper casing in g2p pipeline (i6_core job update)

issue: rwth-i6/i6_core#177
pull: rwth-i6/i6_core#184

### CODE REVIEW

**Review by JackTemaki — CHANGES_REQUESTED** [review]
This would break the existing LibriSpeech jobs, which is especially problematic for the ones that are already exportet to `/work/common`. 

The casing needs to be configurable, and set to "upper" for the LibriSpeech lexicon pipeline.

**Comment by christophmluscher** [comment]
the casing is now configurable. for librispeech set to "upper" which should not break the hashes. the corresponding pull request for `i6_core` is rwth-i6/i6_core#184

I think the hash test is failing because in `i6_core` the corresponding pull request is not merged yet.. @JackTemaki yes??

**Comment by christophmluscher** [comment]
I would only merge, after merging the pull request in `i6_core` and the hash test does not fail.

**Comment by christophmluscher** [comment]
@JackTemaki ping :)

**Pull request merged**
