### PR TITLE
cut and stitch job: modify parallelization

### PR DESCRIPTION
**Pull request by vieting**
The `CutAndStitchSpeechSegmentsFromCorpusJob` currently does parallelization via `multiprocessing.Pool`. This is limited by the number of workers available on a single node. This PR modifies the job to parallelize via splitting the list of recordings and processing a subset of the recordings in each job split. This is also more in line with how we parallelize in other jobs.

Adding @dierkes-j for visibility since you wrote the job in the first place, but I cannot add you as a reviewer. Please feel free to comment.

### CODE REVIEW

**Comment by dierkes-j** [comment]
We should add `ogg` to `assert file_extension in ["wav", "flac", "mp3"]`  and adjust this in the doc string of the job.

**Comment by vieting** [comment]
> We should add `ogg` to `assert file_extension in ["wav", "flac", "mp3"]` and adjust this in the doc string of the job.

That is a different topic. This PR is about the parallelization. Adding ogg can be a helpful extension, but it would be better to open a separate PR for that imho.

**Comment by dierkes-j** [comment]
> > We should add `ogg` to `assert file_extension in ["wav", "flac", "mp3"]` and adjust this in the doc string of the job.
> 
> That is a different topic. This PR is about the parallelization. Adding ogg can be a helpful extension, but it would be better to open a separate PR for that imho.

Yes, correct. I will do a PR for this adjustment.

**Comment by dierkes-j** [comment]
I checked the PR and it looks good to me.

**Pull request merged**
