### PR TITLE
Adding Transducer training stage 3 for SCF

### PR DESCRIPTION
**Pull request by Max-Ryujin**
- added stage 3 for SCf
 - should be nearly identical to lgm stage 3 with name changes and a different `reduction-subtrahend`

### CODE REVIEW

**Review by vieting — COMMENTED** [review]
Looks good to me. Did you run the training to test everything?

**Comment by Max-Ryujin** [comment]
RASR path needs some updates to include all needed libraries. Right now `libpython3.8.so.1.0` is missing for multiple jobs.

**Review by vieting — COMMENTED** [review]
Now you reduced the reduction subtrahend by 1 for the recognition on the training set, but not for the final recognition. That seems inconsistent.

**Comment by Max-Ryujin** [comment]
Is there a way to make sure it is also needed for the final recognition without waiting for the training to finish?

**Comment by vieting** [comment]
> Is there a way to make sure it is also needed for the final recognition without waiting for the training to finish?

Yes, but I'm not sure if the effort is needed. I'd just reduce it for the final recognition as well and if that causes issues we might further investigate.

**Pull request merged**
