### PR TITLE
add option for unknown phoneme

### PR DESCRIPTION
**Pull request by christophmluscher**
adds a flag to add an option for unknown phoneme mapping

### CODE REVIEW

**Review by michelwi — COMMENTED** [review]
How wil RASR behave in training if the unknown lemma has no phonemic representation and an unknown word appears in the transcript?

**Comment by JackTemaki** [comment]
> How wil RASR behave in training if the unknown lemma has no phonemic representation and an unknown word appears in the transcript?

Good questions, but I just found out that I need this flag for the CTC setup as well, so thanks @christophmluscher for adding this.

**Review by JackTemaki — APPROVED** [review]

**Comment by christophmluscher** [comment]
> How wil RASR behave in training if the unknown lemma has no phonemic representation and an unknown word appears in the transcript?

I have no unknown lemma in training. And the unknown symbol got zero weights. Thats why a I added to check if there are performance differences. You basically dont have to consider the unknown phoneme in CART and so on

**Comment by JackTemaki** [comment]
I just saw that the docstrings are missing, I will add them now.

**Pull request merged**
