### PR TITLE
User setup: add setup for ILM chapter

### PR DESCRIPTION
**Pull request by michelwi**
This adds the setup I used for the ILM chapter of my thesis.

Mostly copied + minor modification of `users/zeineldeen/experiments/conformer_att_2022/`
Main purpose of this PR is so I can write I published my setup.

### CODE REVIEW

**Comment by albertz** [comment]
> so I can write I published my setup.

But you can write that anyway? I just put a link to the directory of the setup.

**Comment by michelwi** [comment]
But then external people (and I, after finishing the defense) cannot access the folder and look at the implementation details.

**Comment by albertz** [comment]
I don't understand? For example, see here: https://github.com/rwth-i6/i6_experiments/tree/main/users/zeyer/experiments/exp2024_04_23_baselines

All external people can access that folder and see all implementation details?

**Comment by michelwi** [comment]
Yes in the same fashion I added users/michel/experiments/conformer_att_2022 in this commit and I plan to put exactly this link.

I thought with
>  I just put a link to the directory of the setup.

you meant I should not push the setup but instead give the path to the setup folder on /work/asr3

**Comment by albertz** [comment]
Ah ok, but my question mostly was, why did you do a PR for this? I just push my stuff to my user dir without PRs.

**Pull request merged**
