### PR TITLE
Example report format

### PR DESCRIPTION
**Pull request by Atticus1806**
https://github.com/rwth-i6/i6_core/pull/314

### CODE REVIEW

**Comment by Atticus1806** [comment]
Date and Command are nothing you can pass as an argument since this would restart the job each time you start sisyphus. So since this is only a minimal example I cut them.

**Comment by Atticus1806** [comment]
Then I think this can be merged too. @JackTemaki @michelwi @christophmluscher

**Review by JackTemaki — CHANGES_REQUESTED** [review]
black

**Review by JackTemaki — APPROVED** [review]
black fails unrelated, thus approve

**Comment by michelwi** [comment]
@Atticus1806 could you please give us an example output of a typical GMM system so we can also comment on the form of the output? Thanks!

**Comment by michelwi** [comment]
> black fails unrelated, thus approve

yes, albert has already fixed this in a separate commit

**Comment by Atticus1806** [comment]
```
Results:
Step          dev-clean dev-other
Monophone       32.6      64.8
Triphone 08     14.4      43.9
Triphone 10     14.4      45.1
VTLN 08         12.9      40.3
VTLN 10         13.1      39.8
SAT 08          10.2      33.8
SAT 10          10.3      34.5
VTLN+SAT 08      9.7      32.8
VTLN+SAT 10      9.8      32.7
```

**Review by michelwi — APPROVED** [review]
looks good.

**Pull request merged**
