### PR TITLE
Split `nn.py` file

### PR DESCRIPTION
**Pull request by christophmluscher**
THe file was getting quite large, split into several files. Imports should still work

### CODE REVIEW

**Review by Atticus1806 — CHANGES_REQUESTED** [review]
There are no `NnRecogArgs` anymore? This will potentially break setups.

**Comment by JackTemaki** [comment]
> There are no `NnRecogArgs` anymore? This will potentially break setups.

But they are here: https://github.com/rwth-i6/i6_experiments/pull/181/files#diff-2c01418d940f8adb8ebc1306dbe6881188bf8bcb6e15a50cc70a0c9df64e3145R41

or not?

**Comment by Atticus1806** [comment]
Huh, seems like I overlooked that file for some reason.

**Review by JackTemaki — APPROVED** [review]
I can say my existing setups do not break, for everything else @Atticus1806 you have to decide if it is to your liking.

**Review by Atticus1806 — APPROVED** [review]

**Comment by JackTemaki** [comment]
I really hope we can have a reference Hybrid pipeline that is included in the (hash-)tests soon.

**Pull request merged**
